import { BossSchema } from './schema';
export type { BossData, BossPattern } from './schema';
/**
 * Gardien Sans Visage, end of Act I. Three phases: the rotation widens, telegraphs
 * shorten and attacks chain. Phase 3 adds the blink behind Eidra (followed at once by
 * a sweep, then a charge) and rhythmic waves; its slam then brings down the shard rain.
 */
export const guardianData = BossSchema.parse({
  id: 'faceless-guardian',
  name: 'GARDIEN SANS VISAGE',
  subtitle: 'Celui qui n’a jamais désobéi',
  appearance: 'boss',
  arena: 'obedience',
  health: 460,
  contact: 18,
  spawn: { x: 183, y: 2.4 },
  radius: 1.7,
  height: 4.8,
  speed: 2.4,
  movement: 'hover',
  intro: 2.2,
  transition: 1.6,
  phases: [0.6, 0.28],
  haste: [1, 0.82, 0.68],
  patterns: [
    {
      id: 'sweep',
      kind: 'sweep',
      windup: 1.0,
      recover: 1.0,
      damage: 24,
      range: 4.5,
      combo: { pattern: 'charge', phase: 2 },
      cue: 'BALAYAGE — PARADE OU ESQUIVE',
    },
    {
      id: 'slam',
      kind: 'slam',
      windup: 1.3,
      recover: 1.3,
      damage: 28,
      range: 11,
      combo: { pattern: 'rain', phase: 3 },
      cue: 'ONDE — SAUTEZ',
    },
    {
      id: 'charge',
      kind: 'charge',
      windup: 1.1,
      recover: 1.3,
      damage: 26,
      range: 3,
      cue: 'CHARGE — ESQUIVEZ',
    },
    // Shards of the vault ceiling fall where the ground is marked.
    {
      id: 'rain',
      kind: 'rain',
      phase: 2,
      windup: 1.2,
      recover: 1.0,
      damage: 20,
      range: 2.6,
      count: 5,
      cue: 'PLUIE D’ÉCLATS — QUITTEZ LES MARQUES',
    },
    // Signature: obedience. Whoever moves under his gaze is struck.
    {
      id: 'command',
      kind: 'command',
      phase: 2,
      windup: 1.2,
      recover: 1.1,
      damage: 20,
      range: 1,
      count: 4,
      cue: 'OBÉISSEZ — NE BOUGEZ PLUS',
    },
    {
      id: 'blink',
      kind: 'blink',
      phase: 3,
      windup: 0.75,
      recover: 0.3,
      damage: 0,
      range: 2.8,
      combo: { pattern: 'sweep', phase: 3 },
      cue: 'IL DISPARAÎT — RETOURNEZ-VOUS',
    },
    {
      id: 'nova',
      kind: 'nova',
      phase: 3,
      windup: 1.3,
      recover: 1.4,
      damage: 22,
      range: 11,
      count: 3,
      cue: 'ONDES SUCCESSIVES — SAUTEZ EN RYTHME',
    },
  ],
});
