import { BossSchema } from './schema';
/**
 * Ilyra, end of Act II: the one who refused to see. Quick and evasive where the
 * Guardian is heavy — mirror charges that come back, fans of shards, petals falling
 * on marks, then thorns, blinks and a closing bloom of waves.
 */
export const ilyraData = BossSchema.parse({
  id: 'ilyra',
  name: 'ILYRA',
  subtitle: 'Celle qui refusait de voir',
  appearance: 'ilyra',
  arena: 'denial',
  health: 560,
  contact: 16,
  spawn: { x: 394, y: 2.2 },
  radius: 1.2,
  height: 3.8,
  speed: 3,
  movement: 'glide',
  intro: 2.4,
  transition: 1.8,
  phases: [0.66, 0.33],
  haste: [1, 0.8, 0.65],
  patterns: [
    {
      id: 'petals',
      kind: 'rain',
      windup: 1.1,
      recover: 0.9,
      damage: 18,
      range: 2.2,
      count: 6,
      cue: 'PÉTALES — QUITTEZ LES MARQUES',
    },
    {
      id: 'mirror',
      kind: 'charge',
      windup: 0.9,
      recover: 1.1,
      damage: 24,
      range: 3,
      combo: { pattern: 'mirror-back', phase: 2 },
      cue: 'REFLET — ESQUIVEZ LA CHARGE',
    },
    {
      id: 'mirror-back',
      kind: 'charge',
      followUp: true,
      windup: 0.75,
      recover: 1.1,
      damage: 24,
      range: 3,
      cue: 'ELLE REVIENT — ESQUIVEZ',
    },
    {
      id: 'veil',
      kind: 'volley',
      windup: 1.0,
      recover: 1.0,
      damage: 16,
      range: 9,
      count: 3,
      cue: 'VOILE — ÉVITEZ LES ÉCLATS',
    },
    {
      id: 'thorns',
      kind: 'slam',
      phase: 2,
      windup: 1.2,
      recover: 1.2,
      damage: 24,
      range: 11,
      cue: 'RONCES — SAUTEZ',
    },
    {
      id: 'blink',
      kind: 'blink',
      phase: 2,
      windup: 0.65,
      recover: 0.3,
      damage: 0,
      range: 2.6,
      combo: { pattern: 'cut', phase: 2 },
      cue: 'ELLE S’EFFACE — RETOURNEZ-VOUS',
    },
    {
      id: 'cut',
      kind: 'sweep',
      followUp: true,
      windup: 0.8,
      recover: 1.0,
      damage: 22,
      range: 4,
      cue: 'TAILLE — PARADE OU ESQUIVE',
    },
    // Signature: denial. She hides among reflections of herself.
    {
      id: 'reflections',
      kind: 'mirror',
      phase: 2,
      windup: 1.0,
      recover: 0.8,
      damage: 14,
      range: 1,
      count: 2,
      duration: 7,
      cue: 'REFLETS — TROUVEZ LA VRAIE',
    },
    {
      id: 'bloom',
      kind: 'nova',
      phase: 3,
      windup: 1.4,
      recover: 1.3,
      damage: 20,
      range: 11,
      count: 4,
      cue: 'FLORAISON — SAUTEZ EN RYTHME',
    },
  ],
});
