import { BossSchema } from './schema';
/**
 * Le Porteur du dernier ordre, guardian of the threshold (Act I). He marches in heavy
 * steps and fights with a cleaver; his signature is the standard of the old order,
 * planted in the ground, which keeps sending waves long after he has moved on.
 */
export const keeperData = BossSchema.parse({
  id: 'keeper',
  name: 'LE PORTEUR DU DERNIER ORDRE',
  subtitle: 'Il garde encore le seuil',
  appearance: 'keeper',
  arena: 'last-order',
  health: 260,
  contact: 16,
  spawn: { x: 155, y: 1.36 },
  radius: 0.72,
  height: 2.88,
  speed: 1.8,
  movement: 'march',
  intro: 1.6,
  transition: 1.2,
  phases: [0.5],
  haste: [1, 0.8],
  patterns: [
    {
      id: 'cleave',
      kind: 'sweep',
      windup: 0.95,
      recover: 1.1,
      damage: 24,
      range: 3.4,
      combo: { pattern: 'backswing', phase: 2 },
      cue: 'TAILLE — PARADE OU ESQUIVE',
    },
    {
      id: 'backswing',
      kind: 'sweep',
      followUp: true,
      windup: 0.8,
      recover: 1.1,
      damage: 22,
      range: 3.4,
      cue: 'REVERS — ESQUIVEZ',
    },
    {
      id: 'lunge',
      kind: 'charge',
      windup: 1.0,
      recover: 1.3,
      damage: 24,
      range: 3,
      cue: 'ASSAUT — ESQUIVEZ',
    },
    {
      id: 'standard',
      kind: 'standard',
      windup: 1.1,
      recover: 0.9,
      damage: 18,
      range: 11,
      duration: 5,
      cue: 'ÉTENDARD — SAUTEZ LES ONDES',
    },
    {
      id: 'decree',
      kind: 'slam',
      phase: 2,
      windup: 1.2,
      recover: 1.2,
      damage: 26,
      range: 11,
      combo: { pattern: 'standard', phase: 2 },
      cue: 'DÉCRET — SAUTEZ',
    },
  ],
});
