import { z } from 'zod';
export const EnemySchema = z.object({
  id: z.string(),
  name: z.string(),
  health: z.number().positive(),
  damage: z.number().positive(),
  speed: z.number().nonnegative(),
  range: z.number().positive(),
  detection: z.number().positive(),
  stagger: z.number().nonnegative(),
  windup: z.number().positive(),
  recover: z.number().positive(),
  drops: z.number().int().nonnegative(),
  ranged: z.boolean(),
  scale: z.number().positive(),
  /** Damage dealt by touching the body; dashing through it is safe. */
  contact: z.number().nonnegative(),
  /** Flies over the floor instead of walking on it. */
  flying: z.boolean().default(false),
});
export const enemyData = {
  keeper: EnemySchema.parse({
    id: 'keeper',
    name: 'LE PORTEUR DU DERNIER ORDRE',
    health: 120,
    damage: 24,
    speed: 1.4,
    range: 2.5,
    detection: 9,
    stagger: 0.14,
    windup: 1.1,
    recover: 1.7,
    drops: 8,
    ranged: false,
    scale: 1.65,
    contact: 16,
  }),
  watcher: EnemySchema.parse({
    id: 'watcher',
    name: 'Veilleur fêlé',
    health: 36,
    damage: 16,
    speed: 2.2,
    range: 1.8,
    detection: 10,
    stagger: 0.25,
    windup: 0.75,
    recover: 1.1,
    drops: 2,
    ranged: false,
    scale: 1,
    contact: 10,
  }),
  wisp: EnemySchema.parse({
    id: 'wisp',
    name: 'Souvenir errant',
    health: 24,
    damage: 12,
    speed: 1.4,
    range: 8,
    detection: 12,
    stagger: 0.3,
    windup: 1.05,
    recover: 1.6,
    drops: 2,
    ranged: true,
    scale: 0.75,
    contact: 8,
    flying: true,
  }),
  sentinel: EnemySchema.parse({
    id: 'sentinel',
    name: 'Porteur de cendres',
    health: 64,
    damage: 23,
    speed: 1.4,
    range: 2.5,
    detection: 9,
    stagger: 0.14,
    windup: 1.1,
    recover: 1.7,
    drops: 4,
    ranged: false,
    scale: 1.35,
    contact: 14,
  }),
};
export type EnemyKind = keyof typeof enemyData;
export type EnemyData = z.infer<typeof EnemySchema>;
