import { z } from 'zod';
export const EnemySchema = z.object({
  id: z.string(),
  name: z.string(),
  health: z.number().positive(),
  damage: z.number().positive(),
  speed: z.number().nonnegative(),
  range: z.number().positive(),
  detection: z.number().positive(),
  stagger: z.number().nonnegative(),
  windup: z.number().positive(),
  recover: z.number().positive(),
  drops: z.number().int().nonnegative(),
  ranged: z.boolean(),
  scale: z.number().positive(),
  /** Damage dealt by touching the body; dashing through it is safe. */
  contact: z.number().nonnegative(),
  /** Flies over the floor instead of walking on it. */
  flying: z.boolean().default(false),
  /** Blows (or shots) chained before recovering; follow-ups wind up faster. */
  combo: z.number().int().min(1).default(1),
  /** Metres the body lunges forward during each blow. */
  lunge: z.number().nonnegative().default(0),
  /** Health ratio under which it enrages: quicker windups, recoveries and steps. */
  enrage: z.number().min(0).max(1).default(0),
  /** Speed of its shots, metres per second. */
  projectileSpeed: z.number().positive().default(7),
});
export const enemyData = {
  // Act I elite: a banner-bearer that chains two cleaves with lunges, three when enraged.
  keeper: EnemySchema.parse({
    id: 'keeper',
    name: 'LE PORTEUR DU DERNIER ORDRE',
    health: 180,
    damage: 24,
    speed: 1.6,
    range: 2.5,
    detection: 9,
    stagger: 0.12,
    windup: 0.95,
    recover: 1.4,
    drops: 10,
    ranged: false,
    scale: 1.65,
    contact: 16,
    combo: 2,
    lunge: 2.2,
    enrage: 0.5,
  }),
  watcher: EnemySchema.parse({
    id: 'watcher',
    name: 'Veilleur fêlé',
    health: 36,
    damage: 16,
    speed: 2.2,
    range: 1.8,
    detection: 10,
    stagger: 0.25,
    windup: 0.75,
    recover: 1.1,
    drops: 2,
    ranged: false,
    scale: 1,
    contact: 10,
  }),
  wisp: EnemySchema.parse({
    id: 'wisp',
    name: 'Souvenir errant',
    health: 24,
    damage: 12,
    speed: 1.4,
    range: 8,
    detection: 12,
    stagger: 0.3,
    windup: 1.05,
    recover: 1.6,
    drops: 2,
    ranged: true,
    scale: 0.75,
    contact: 8,
    flying: true,
  }),
  sentinel: EnemySchema.parse({
    id: 'sentinel',
    name: 'Porteur de cendres',
    health: 64,
    damage: 23,
    speed: 1.4,
    range: 2.5,
    detection: 9,
    stagger: 0.14,
    windup: 1.1,
    recover: 1.7,
    drops: 4,
    ranged: false,
    scale: 1.35,
    contact: 14,
    combo: 2,
    lunge: 1.2,
  }),
  // Act II: low, fast ash beast that lunges at Eidra.
  crawler: EnemySchema.parse({
    id: 'crawler',
    name: 'Rampant de cendre',
    health: 44,
    damage: 14,
    speed: 3.4,
    range: 1.6,
    detection: 11,
    stagger: 0.2,
    windup: 0.55,
    recover: 0.9,
    drops: 3,
    ranged: false,
    scale: 0.85,
    contact: 10,
    lunge: 2.4,
  }),
  // Act II: keeps its distance and throws three embers in a row.
  ember: EnemySchema.parse({
    id: 'ember',
    name: 'Porte-braise',
    health: 40,
    damage: 12,
    speed: 1.2,
    range: 9,
    detection: 13,
    stagger: 0.3,
    windup: 0.9,
    recover: 1.6,
    drops: 3,
    ranged: true,
    scale: 1,
    contact: 8,
    combo: 3,
    projectileSpeed: 9,
  }),
  // Act II elite of the Brasier: three lunging cleaves, faster still when enraged.
  warden: EnemySchema.parse({
    id: 'warden',
    name: 'LA SENTINELLE DE CENDRE',
    health: 280,
    damage: 26,
    speed: 1.9,
    range: 2.8,
    detection: 12,
    stagger: 0.1,
    windup: 0.85,
    recover: 1.3,
    drops: 14,
    ranged: false,
    scale: 1.85,
    contact: 18,
    combo: 3,
    lunge: 3.2,
    enrage: 0.5,
  }),
};
export type EnemyKind = keyof typeof enemyData;
export type EnemyData = z.infer<typeof EnemySchema>;
