export enum InputAction {
  Left = 'left',
  Right = 'right',
  Walk = 'walk',
  Jump = 'jump',
  Dash = 'dash',
  Attack = 'attack',
  Charge = 'charge',
  Parry = 'parry',
  Remanence = 'remanence',
  Echo = 'echo',
  Interact = 'interact',
  Map = 'map',
  Pause = 'pause',
}
export const defaultBindings: Record<InputAction, string> = {
  left: 'KeyA',
  right: 'KeyD',
  walk: 'ControlLeft',
  jump: 'Space',
  dash: 'ShiftLeft',
  attack: 'KeyJ',
  charge: 'KeyK',
  parry: 'KeyL',
  remanence: 'KeyQ',
  echo: 'KeyR',
  interact: 'KeyE',
  map: 'Tab',
  pause: 'Escape',
};
export const actionLabels: Record<InputAction, string> = {
  left: 'Aller à gauche',
  right: 'Aller à droite',
  walk: 'Marcher',
  jump: 'Sauter',
  dash: 'Esquive',
  attack: 'Attaque légère',
  charge: 'Attaque chargée',
  parry: 'Parade',
  remanence: 'Rémanence',
  echo: 'Memory Step',
  interact: 'Interagir',
  map: 'Carte',
  pause: 'Pause',
};
